/**
 * @file StepperMotor.h
 * @brief Driver for StepperMotor
 * @version 0.1
 * @date 2026-03-27
 * 
 * @copyright Copyright (c) 2026
 * 
 */
#pragma once

// *** INCLUDES ***
#include <cstdint>
#include <cstdlib>
#include <pico/stdlib.h>
#include <hardware/pio.h>
#include <hardware/dma.h>
#include <hardware/gpio.h>

#include "stepper.pio.h"      // generated by CMake from stepper.pio

// *** NAMESPACE ***
namespace Steckinator {
    

    
    class StepperMotor {
    public:


        /**
         * Construct and fully initialise a stepper motor.
         *
         * @param pio       PIO block to use (pio0 or pio1).
         *                  The PIO program is loaded once per block and shared.
         * @param stateMachineIndex         State machine index (0–3). Each motor needs its own.
         * @param pinStep                   GPIO for STEP output.
         * @param dirPin                    GPIO for DIR  output.
         */
        void Init(PIO pio, uint stateMachineIndex, uint pinStep, uint pinDir);


        void Move(int32_t steps);

    private:
        
        // ** Members ** 
        PIO m_pio;
        uint m_stateMachineIndex;
        uint m_pinStep;
        uint m_pinDir;

    };
}