/**
 * @file StepperMotor.h
 * @brief Driver for StepperMotor
 * @version 0.1
 * @date 2026-03-27
 * 
 * @copyright Copyright (c) 2026
 * 
 */
#pragma once

// *** INCLUDES ***
#include <cstdint>
#include <cstdlib>
#include <vector>
#include <pico/stdlib.h>
#include <hardware/pio.h>
#include <hardware/dma.h>
#include <hardware/gpio.h>

#include "stepper.pio.h"      // generated by CMake from stepper.pio

// *** NAMESPACE ***
namespace Steckinator {
    
    using Steps = int32_t;

    
    class StepperMotor {
    public:

        /**
         * @brief Construct and fully initialise a stepper motor.
         * 
         * @param pio                       PIO block to use (pio0 or pio1).
         * @param stateMachineIndex         State machine index (0–3). Each motor needs its own.
         * @param programOffset             The program offset of the pio driver
         * @param pinStep                   GPIO for STEP output
         * @param pinDir                    GPIO for DIR output
         * @param stepsPerMm                [steps/mm]
         */
        void Init(PIO pio, uint stateMachineIndex, uint programOffset, uint pinStep, uint pinDir, uint stepsPerMm);


        enum class AccelerationMethod {
            NONE = 0,
            RAMP
        };

        /**
         * @brief Move a relative amount of steps
         * 
         * @param steps                 The steps to move
         * @param feedrate              The feedrate
         * @param accelerationMethod    The acceleration profile to use
         */
        void MoveRelative(Steps steps, float feedrate, AccelerationMethod accelerationMethod);
        
        /**
         * @brief Stops the motor immediately
         * 
         */
        void Stop();

        /**
         * @brief Checks if the motor is still executing the previous move
         * 
         * @return true motor is busy, else false
         */
        bool IsBusy();

        /**
         * @brief Gets the offset of the stepper pio program
         * 
         * @param pio       The pio to use
         * @return uint     The program offset
         */
        static uint GetStepperProgramOffset(PIO pio) { return pio_add_program(pio, &stepper_program);}

    private:

        /**
         * @brief Build the step table with a ramp acceleration profile 
         * 
         * @param total_steps   number of total steps
         * @param feedrate      target feedrate [mm/s]
         */
        void BuildStepTable_Ramp(uint32_t total_steps, float feedrate);

        /**
         * @brief Build the step table with a constant profile 
         * 
         * @param total_steps   number of total steps
         * @param feedrate      target feedrate [mm/s]
         */
        void BuildStepTable_Constant(uint32_t total_steps, float feedrate);

    private:
        
        // ** Members ** 
        uint m_pinStep;                 // The STEP pin of the driver
        uint m_pinDir;                  // The DIR pin of the driver


        PIO m_pio = nullptr;            // The underlying pio
        uint m_stateMachineIndex = -1;  // The state machine index of the pio
        uint m_programOffset;
        uint m_dmaChannel = -1;         // The dma channel for the pio


        float m_stepsPerMm = 0.f;                   // steps per millimeter – set according to your mechanics
        const uint32_t m_initialPeriodUs = 5000;    // starting period (slow speed) in microseconds
        std::vector<uint32_t> m_stepTable;          // The table containing the step pulses

    };
}